name: "Test opensearch-reindexer"
description: "Run the tests for opensearch-reindexer"

runs:
  using: "composite"

  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      shell: bash
      run: make install

    - name: Test with pytest
      shell: bash
      run: make test
